### ISSUE TITLE
Should be able to get verbosity level from CLILogging

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#19]
`determine_verbose_level` requires args and as it is only called as part of configure, it should be an internal level method. However, whatever value is determined in configure should be saved as a property so I can access it simply using `ctx.logging.verbose_level` or something similar. Now I'm trying to jump through hoops to get this piece of information that should be readily available.

**Comment by derekbekoe** [comment]
It's supposed to deter logic that is based on the current logging level.
Writing code that's based on the log level could behave in unexpected ways.

For example, when file logging is enabled, there are two log levels, one for console and a different one for file logging.

We can still expose it from knack though.

**Comment by tjprescott** [comment]
Progress info in the CLI for deployments is only supposed to show when --verbose (or higher presumably) is shown. Since the code does actually make this determination internally, it would be nice to preserve this.  Or we could make a better way of deciding when to show progress in the Az, but I'm going for a translation right now. :)

**Comment by derekbekoe** [comment]
There are a few things I can do but want to clarify:

**(1) If you want to do exactly as in the CLI currently, this is currently possible without changing anything in knack**
```
import logging
from knack.log import get_logger
logger = get_logger()
is_verbose = any(handler.level <= logging.INFO for handler in logger.handlers)
```
This is what we do in the CLI right now [here](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/__init__.py#L215).
This will return `is_verbose==True` if `--verbose`/`--debug` are provided OR file logging has been enabled (because the handler for file logging has a log level on DEBUG).

** (2) The above should be in knack **
If you want to do the above without having to write that logic yourself, I can expose a property on `ctx.logging` that return the current lowest log level (the min of the log level of all handlers).

Then, you can have a check like `is_verbose = True if ctx.logging.log_level_cli <= logging.INFO else False`.

** (3) You only want the log level for the console log (ignore the file log level) **
I can do this also but that's not what currently happens in the CLI in (1).

With this change, `ctx.logging.log_level_cli` would refer to the actual console log level only so if user uses `--verbose`, it would be `logging.INFO` and if they specify `--debug` it would be `logging.DEBUG`.

https://docs.python.org/2/library/logging.html#logging-levels

**Comment by derekbekoe** [comment]
I can still make `determine_verbose_level` private though.
