### ISSUE TITLE
pyyaml security warning

### ISSUE THREAD

**Issue by haroldrandom** [microsoft/knack#193]
![image](https://user-images.githubusercontent.com/14357159/78351588-a4b68700-75d9-11ea-8b73-255cf4ba3edf.png)

[This build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=343581&view=logs&j=74095127-2a27-5370-37ed-15a4193f243f&t=a1e0e2fa-9206-5f67-cee4-df0dbeea0a5f&l=1227)

**Comment by yonzhan** [comment]
pyyaml security warning

**Comment by jiasli** [comment]
Similar to https://github.com/Azure/azure-cli/issues/12428, which is fixed by https://github.com/Azure/azure-cli/pull/12440. I think we need to bump to higher versions.

**Comment by Quinncuatro** [comment]
@jiasli - It's been two years, and somehow the line for PyYAML in `requirements.txt` no longer has a specified point release associated with it.

I'm getting a similar warning as @haroldrandom, since the Azure-CLI package is pulling in `knack/0.9.0` which is pulling in `PyYAML/5.3.1`.

I brought it up in Issue #258.

**Comment by Quinncuatro** [comment]
I take that back. Everything was resolved in #258. Ended up being an issue with the pipeline.
