### ISSUE TITLE
CLICommandsLoader Recommended Changes

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#35]
Based on ongoing conversion work in CLI 2.0, consider the below listed changes to CLICommandsLoader. The purpose of these would be to simplify the command authoring process, as the author need only focus on the public methods of the CommandLoader class. 

- [ ] 1. Make "create_command" private. This should be reached by invoking "command" on a command group. This method is currently public and presents an alternate, non-favored way of creating commands. `get_op_handler` and `user_confirmed` also seem to be internal implementation details and might be better of being private.
- [ ] 2. Allow `__init__` to take `**kwargs` and save them in the loader's instance.  This is used by the CLI to accomplish various scenarios that eliminate coding redundancy (for example, settings the default resource_type in a module).
- [ ] 3. Expose public methods `argument_context` and `command_group` that wrap the import and instantiation of ArgumentContext and CommandGroup respectively. This makes it easier to instantiate these things because the author doesn't have to remember to import these classes and allows the author to simply focus on the public interface of the command loader to accomplish everything (s)he needs.
- [ ] 4. Remove "CommandSuperGroup" as it is a nebulous concept that came from a nebulous concept in CLI 2.0. Module_name can be upleveled to the CLICommandsLoader metadata, and "operations_tmpl" can be downleveled to the CommandGroup.
- [ ] 5. Add a CLICommandType class which is a reusable bundle of kwargs, analogous to CLIArgumentType. Allow CommandGroup to accept this type, overriding its values based on any additional kwargs. These `group_kwargs` would then serve as the baseline for any subsequent calls to `group.command(...)`
- [ ] 6. ...and in the spirit of improvement, maybe "CLICommandModule" would be a more intuitive class name. It's definitely how I mentally think of it.

**Comment by derekbekoe** [comment]
**Done:**
1. I've made `get_op_handler` and `user_confirmed` private. `create_command()` is a method I expect may be overridden so not marked that as private.
4. Removed "CommandSuperGroup" and removed `module_name` since it's not actually used.

**Not done / Open to discussion:**
2. Knack wouldn't use these `kwargs` so would rather leave that up to the caller to subclass the command loader if they want this.
3. Going to leave knack without this for now. If it does become beneficial, we can add it later. Right now, I think there's a single clear way to do it.
5. I believe the same thing can be achieved by just using kwargs on CommandGroup. Not sure what benefit wrapping it in CLICommandType does?
6. I'd prefer not to bring the concept of 'command modules' into Knack.
