### ISSUE TITLE
Table output does not honor OrderedDict

### ISSUE THREAD

**Issue by tjprescott** [Microsoft/knack#56]
There's a test failure in CLI 2.0 that is testing a table formatter (ComputeListSkusScenarioTest).  The formatter is a callable that produces a list of OrderedDicts.  However, the resulting table output is not in the same order that the values are added to the OrderedDict.

**Comment by mattjegan** [comment]
I'd like to give this issue a shot, I can probably look at getting a PR up in the next 12 hours or so.

**Comment by mattjegan** [comment]
@tjprescott I was a little confused about what the desired behaviour is, I have altered a test to demonstrate what I believe you're asking for here (#100). If this is correct, I'll continue on a fix.

**Comment by tjprescott** [comment]
The purpose of using OrderedDict for the table format is so that the table columns will appear in the same order. However, that test is showing this is not happening.

**Comment by mattjegan** [comment]
Awesome, thanks, I'll take a look at fixing this later.

**Comment by atbagga** [comment]
> The purpose of using OrderedDict for the table format is so that the table columns will appear in the same order. However, that test is showing this is not happening.

@tjprescott  I think it is following the order unless you override in your transformer (I think that is the case with transform_sku_for_table_output where the issue is reported) or if you do not have a transformer then the behavior is to sort the keys.

I see the three tests 1. test_out_table, 2. test_out_table_no_query_no_transformer_order, 3. test_out_table_no_query_yes_transformer_order displaying the same behavior. 

I might be understanding it wrong, please let me know.

**Comment by tjprescott** [comment]
@atbagga I believe you are right. When I create a table transformed using OrderedDict, I have no issues with the column ordering. Closing this.
